#include "ai_model.h"

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#ifdef STM32_TARGET
#include "stm32f4xx_hal.h"
#include <string.h>

UART_HandleTypeDef huart2;

static void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_USART2_UART_Init(void);

static void uart_print(const char *message)
{
    HAL_UART_Transmit(&huart2, (uint8_t *)message, strlen(message), HAL_MAX_DELAY);
}
#else
static void uart_print(const char *message)
{
    (void)message;
}
#endif

static void print_inference(const float *output)
{
#ifdef STM32_TARGET
    char buffer[128];
    int len = snprintf(buffer, sizeof(buffer),
                       "AI output: [%.3f, %.3f, %.3f]\r\n", output[0], output[1], output[2]);
    if (len > 0)
    {
        uart_print(buffer);
    }
#else
    printf("AI output: [%.3f, %.3f, %.3f]\n", output[0], output[1], output[2]);
#endif
}

int main(void)
{
#ifdef STM32_TARGET
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_USART2_UART_Init();

    uart_print("STM32 AI inference example\r\n");
#else
    printf("STM32 AI inference example (host build)\n");
#endif

    const float input[AI_MODEL_INPUT_DIM] = {5.1f, 3.5f, 1.4f, 0.2f};
    float output[AI_MODEL_OUTPUT_DIM];

    ai_model_forward(input, output);
    print_inference(output);

#ifdef STM32_TARGET
    while (1)
    {
        HAL_Delay(1000);
    }
#else
    return 0;
#endif
}

#ifdef STM32_TARGET
static void SystemClock_Config(void)
{
    /* Replace this function with the version generated by STM32CubeMX for your MCU. */
}

static void MX_GPIO_Init(void)
{
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
}

static void MX_USART2_UART_Init(void)
{
    __HAL_RCC_USART2_CLK_ENABLE();

    huart2.Instance = USART2;
    huart2.Init.BaudRate = 115200;
    huart2.Init.WordLength = UART_WORDLENGTH_8B;
    huart2.Init.StopBits = UART_STOPBITS_1;
    huart2.Init.Parity = UART_PARITY_NONE;
    huart2.Init.Mode = UART_MODE_TX_RX;
    huart2.Init.HwFlowCtl = UART_HWCONTROL_NONE;
    huart2.Init.OverSampling = UART_OVERSAMPLING_16;

    if (HAL_UART_Init(&huart2) != HAL_OK)
    {
        while (1)
        {
        }
    }
}
#endif
